export const axisOptions = [
  { label: 'Weapon Class', field: 'damageType' },
  { label: 'Obtained By', field: 'obtained' },
  { label: 'Rarity', field: 'rarity' },
  { label: 'Knockback', field: 'knockback' },
  { label: 'Speed', field: 'speed' },
  { label: 'Subclass', field: 'subclass', order: [
    'Swords',
    'Spears',
    'Yo-yo',
    'Boomerangs',
    'Flails',
    'Bows',
    'Guns',
    'Launchers',
    'Specialist',
    'Wands',
    'Magic guns',
    'Spell tomes',
    'Summons',
    'Sentries',
    'Whips',
  ]},
  { label: 'Unlocked', field: 'progression tier', rename: {
    'Pre-Wall of Flesh': 'Pre-WoF',
    'Pre-mechanical bosses': 'Pre-Mech',
    'Pre-Lunatic Cultist': 'Pre-Cultist',
  }, order: [
    'Pre-Bosses',
    'Pre-Skeletron',
    'Pre-Wall of Flesh',
    'Pre-mechanical bosses',
    'Pre-Plantera',
    'Pre-Golem',
    'Pre-Lunatic Cultist',
    'Pre-Moon Lord',
    'Endgame',
  ]},
]
